### PR TITLE
Turn Synchronization and Cache–Database Inconsistency fix

### LINKED ISSUE #27: Turn Synchronization and Cache–Database Inconsistency
The game state was out of sync: Player A’s client shows it’s Player B’s turn, while Player B’s client shows it’s Player A’s turn. We need to investigate the root cause, as it appears the cache and database are not properly synchronized.

### PR DESCRIPTION
**Pull request by Demonofpower**
Closes #27 

We really need to save player information outside of games in the future. Right now we need to iterate over every game in the database to get the games of a player.

### CODE REVIEW

File: Dystopia/Database/Game/PolydystopiaGameRepository.cs [hunk 1]
```diff
@@ -80,9 +82,16 @@ public async Task<GameViewModel> UpdateAsync(GameViewModel gameViewModel)
 
     public async Task<List<GameViewModel>> GetAllGamesByPlayer(Guid playerId)
     {
-        // no need to cache as it is usually not relevant. TODO fix when custom entities are implemented(just have a list of playerid in game)
-        var allGames = await _dbContext.Games.ToListAsync();
-        return allGames
-            .Where(game => _bridge.IsPlayerInGame(playerId.ToString(), game.CurrentGameStateData)).ToList();
+        var _ = _cacheService.TryGetAll(
```
Comment (joukepouke) [inline Dystopia/Database/Game/PolydystopiaGameRepository.cs:85]: This assigns a value to _, to throw away a value use `_ = ...` without var

**Review by joukepouke — CHANGES_REQUESTED** [review]

File: Dystopia/Database/Game/PolydystopiaGameRepository.cs [hunk 2]
```diff
@@ -80,9 +82,16 @@ public async Task<GameViewModel> UpdateAsync(GameViewModel gameViewModel)
...
     {
-        // no need to cache as it is usually not relevant. TODO fix when custom entities are implemented(just have a list of playerid in game)
-        var allGames = await _dbContext.Games.ToListAsync();
-        return allGames
-            .Where(game => _bridge.IsPlayerInGame(playerId.ToString(), game.CurrentGameStateData)).ToList();
+        _cacheService.TryGetAll(
+            model => _bridge.IsPlayerInGame(playerId.ToString(), model.CurrentGameStateData),
+            out var cachedPlayerGames);
+
+        var allDbGames = await _dbContext.Games.ToListAsync();
```
Comment (joukepouke) [inline Dystopia/Database/Game/PolydystopiaGameRepository.cs:89]: Should we not first .Select the gamestate data and id and then query db again to convert to games? I'm unsure but might have a big memory improvement

**Review by joukepouke — APPROVED** [review]
